name: server
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.2.5

dependencies:
  protos:
    path: ../protos

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
